[package]
name = "coverflow"
version = "2.3.0"
edition = "2021"
build = "build.rs"
authors = ["sangyuxiaowu"]
description = "CoverFlow Designer"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
